### ISSUE TITLE
Firefox is showing the borders even on fullscreen

### ISSUE THREAD

**Issue by hrqmonteiro** [matinlotfali/KDE-Rounded-Corners#128]
Other windows, like console, hides the border when on fullscreen, but firefox remains

https://github.com/matinlotfali/KDE-Rounded-Corners/assets/17055027/06d3973f-af5a-4ca5-8dea-b1cd5eb5b925

**Comment by matinlotfali** [comment]
May I have more details about your distro and configurations?

**Comment by matinlotfali** [comment]
I can see that you have unchecked the `Maximized Windows` from your exclusions. If you check it, maximized windows shouldn't have rounded corners.

**Comment by hrqmonteiro** [comment]
> I can see that you have unchecked the `Maximized Windows` from your exclusions. If you check it, maximized windows shouldn't have rounded corners.

Yes, but that was on purpose. But i am not talking about maximized windows, but fullscreen windows.

As i showed in the example, if i put Konsole on fullscreen (not maximized), it hides all of the decoration (as it should be), and the borders from ShapeCorners also hide.

Same thing if i open a video on VLC and put it on fullscreen. But as i showed in the video, if i open a Youtube video on firefox on fullscreen, the borders from ShapeCorners are showing.

**Comment by matinlotfali** [comment]
It looks like Firefox is using the name `navigator`. Removing the navigator from your inclusion list should stop your Firefox from having rounded corners on fullscreen.

**Comment by hrqmonteiro** [comment]
> It looks like Firefox is using the name `navigator`. Removing the navigator from your inclusion list should stop your Firefox from having rounded corners on fullscreen.

But then it also don't show the borders even if not fullscreen. When i have the screen on a normal width or maximized no borders at all.

It seems like I'm not being clear, I'll try to rephrase.

I want to use it to round all of my windows, and have borders on all of the windows, **even maximized**.

But, when i am on a fullscreen window, let's say playing a video on VLC, Google Chrome or Firefox, all of the window decorations should disappear, right?

This works fine on Chrome and VLC, but when i am on Firefox FULLSCREEN (let's say you open a video and double click on it so it goes full screen, as i showed in the video on the issue) it is keeping the borders from ShapeCorners.
The same thing doesn't happen on VLC when i put on fullscreen video. Or if i am on Konsole and press F11. It also hides everything, the correct behavior.


When the windows are not maximized or maximized, they are showing the borders and shadows, which is totally fine, but when i enter fullscreen mode, only firefox is keeping the borders. No matter the rules.


It i remove it from the included windows, it won't show the shadows or the borders are all, that's not what i want, right?

**Comment by matinlotfali** [comment]
I get it now. I will try to add some debug logs to find the difference between Konsole, VLC, and Firefox fullscreen windows.

**Comment by hrqmonteiro** [comment]
> I get it now. I will try to add some debug logs to find the difference between Konsole, VLC, and Firefox fullscreen windows.

Thanks, my man! Appreciate it very much

**Comment by t3n3t** [comment]
> I can see that you have unchecked the `Maximized Windows` from your exclusions. If you check it, maximized windows shouldn't have rounded corners.

Hi there. In my case the 'Maximized Windows' checkbox does nothing. If I just check it, FF in maximized mode still has rounded corners. If I add 'navigator' to exclusions and check this checkbox, FF is stripped of rounded corners regardless of whethere it is maximized or not.
Is this intended behaviour, a bug or am i missing something?

**Comment by matinlotfali** [comment]
> If I just check it, FF in maximized mode still has rounded corners.

Is this only for Firefox? what about other apps?

> If I add 'navigator' to exclusions and check this checkbox, FF is stripped of rounded corners regardless of whethere it is maximized or not.

This is intended.

May I have a screenshot?

**Comment by t3n3t** [comment]
Actually, all maximized apps still feature rounded corners.
![settings](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/8544745/3a570a6a-5f5a-48b2-8b66-02c8996b20c7)
![dolphin](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/8544745/d69b54db-cb73-4352-a80f-3dd1e9d3de4d)
![firefox](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/8544745/f13c094c-626e-4a49-8a98-ab290df272a6)

**Comment by matinlotfali** [comment]
Okay, I see the problem for @t3n3t. When using both vertical and horizontal panels, I am not detecting the maximized state correctly. 

This is probably already fixed in #105 but never got merged because nobody tested it.
Can you give it a try?
Keep in mind that the branch is old. I just want to check the functionality.

**Comment by t3n3t** [comment]
An odd thing - after rebuilding from master branch the effect is still not working at all. I've tried to uninstall it as described in README.md, rebooted, retraced all the install steps, rebooted... am I missing something? After first complete uninstall and reboot the effect was still in the list in settings...

![Screenshot_20240124_214033](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/8544745/220937d4-f387-4981-8c52-cfa73beea399)

**Comment by matinlotfali** [comment]
Ouch. The old and new codes have different installation instructions. Use the `find` command to find files and delete them manually:

```bash
find / -name "*shapecorners*" 2>/dev/null
```

**Comment by t3n3t** [comment]
> Ouch. The old and new codes have different installation instructions. Use the `find` command to find files and delete them manually:
> 
> ```shell
> find / -name "*shapecorners*" 2>/dev/null
> ```

Thanx, I did it and completely rebuilt from master.
Indeed, with only horizontal panels effect works as intended. 
![Screenshot_20240124_221040](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/8544745/b87a88e0-651f-4d4e-a533-ba0a38c56cff)

Sadly, with vertical ones it does not. Hope you will find time to resolve this. So far, amazing job, keep up! :)

**Comment by matinlotfali** [comment]
I did some bug fixes focusing on the panels.
@t3n3t @hrqmonteiro May I ask you to try the #105?

**Comment by t3n3t** [comment]
> I did some bug fixes focusing on the panels. @t3n3t @hrqmonteiro May I ask you to try the #105?

Hey there. Could you please take me step by step do do proper testing? I mean like what branch it should be, do I need to uninstall previos build (and remove all files related to it) and so on. Because last time it took quite a bit of effort and time to get a grasp on it. Thanx in advance, I'll do testing gladly.

**Comment by matinlotfali** [comment]
Absolutely. 

Run the following commands inside the `build` folder:

```bash
sudo make uninstall
cd ..
rm -rf build
git checkout tiles
git pull
mkdir build
cd build
cmake .. --install-prefix /usr
make
sudo make install
```
then reboot

**Comment by t3n3t** [comment]
@matinlotfali Yeah, that did it, thanks man! Now maximized windows does not have rounded corneres when using vertical panels.

**Comment by matinlotfali** [comment]
That is good. I need to test the branch more before I merge it into the master.
